### ISSUE TITLE
Change periods to commas in our data/numbers

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#349]
According to Swedish standards, numbers should not use periods but commas to represent decimals, but currently, periods are used on the site. This would need to be changed, possibly in utils/climateDataService.tsx where the data is loaded from data/output/climate-data.json, but it could also occur elsewhere.

**Comment by LudwikJaniuk** [comment]
Carification - is this for visual presentation only or are changes requested in the actual excel data/python processing?

**Comment by LudwikJaniuk** [comment]
Most likely this only concerns visual presentation. Code changes would likely be syntax-breaking after all.

**Comment by belanglos** [comment]
#511 is about translating the page to english. Would it make sense to adapt the presentation of numbers based on the used locale?

**Comment by Greenheart** [comment]
@belanglos Yes, exactly! Thanks for the suggestion :)

I think we've solved this already, but forgot to close this issue, but I'm not entirely sure.

If you want, you could have a look and verify that emission numbers and similar are formatted based on the user's locale. It could be a good opportunity to learn more about Klimatkollen and what data we present.

We're using `Intl.NumberFormat` to make this happen. Currently since we only support the `sv` locale, we've hardcoded it. But in the future website (which we're working on in parallel to the current website, we will add support for formatting based on the current user locale).

**Comment by elvbom** [comment]
Addressed in #593
