### ISSUE TITLE
Add Readme for absolute beginners

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#408]
Since we are an open-source project, people who are completely new to programming can also contribute. It would be good to have a Readme for absolute beginners on how to get started (with links to installing Git, VSCode, etc) that can be used by those interested, but also at hacks and so forth, as instructions.

**Comment by datalowe** [comment]
Here are some suggestions on things I think would be nice to include in the beginner README:

* Short background explaining what technologies are involved (links to the starting page for React, next.js etc).
* Link to instructions for installing node & npm.
* Short info about the steps involved in creating a pull request
  * In particular an explanation of how one should create a fork of the repository and do PR's through that.
  * Also some short note about how contributors don't have to worry too much about messing anything up, since their contribution will be reviewed before being accepted.

**Comment by LudwikJaniuk** [comment]
Here is my draft: https://github.com/Klimatbyran/klimatkollen/pull/441

Thoughts?
