### ISSUE TITLE
Raw HTML visible briefly on page load 

### ISSUE THREAD

**Issue by jeevikasirwani** [Klimatbyran/klimatkollen#449]

**Comment by Greenheart** [comment]
I think I understand what you mean. I can reproduce this when doing a hard refresh (clearing the browser cache), or when the dev server has just started.

Now the question is what is causing this. Here are some theories to investigate further:
- Maybe this happens because we have a big dataset that is downloaded on the first page?

- Or maybe this is caused by the redirect, causing the app to render only partially before redirecting to the actual route.
  - Perhaps it would be better to navigate to a shallow route instead of using a permanent redirect (which causes Next.js to load another route and render that instead, even though the user sees a very similar page)?
