### ISSUE TITLE
Link to Utsläppsberäkningar report is broken

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#485]
Even though the URL seems correct, the link to the Utsläppsberäkningar report (link at bottom of https://www.klimatkollen.se/utslappsberakningar)

<img width="957" alt="Screenshot 2024-05-02 at 08 32 48" src="https://github.com/Klimatbyran/klimatkollen/assets/7899748/eb7b87a0-504a-437a-8cbc-2df06acb86cc">

yeilds a 404ish page (no 404 text, "Gå till startsidan" at top of screen).

<img width="957" alt="Screenshot 2024-05-02 at 08 33 00" src="https://github.com/Klimatbyran/klimatkollen/assets/7899748/330692eb-f5bc-44ca-b6a5-c647ea177a60">

When reloaded, correct pdf is displayed (https://www.klimatkollen.se/utslappsberakningar.pdf).

**Comment by Greenheart** [comment]
I think this is caused by how Next.js handles links, trying to preload all internal links as if they are pages. However, in this case, we want to treat it like an external link to be opened in a separate page, and most importantly ignoring the Next.js link handling/preloading.

**Comment by Greenheart** [comment]
More info: Next.js attempts to prefetch data for static PDFs coming from the same site. It seems to treat all internal links as safe for prefetching, rather than checking if it matches an actual route.

![image](https://github.com/Klimatbyran/klimatkollen/assets/6125097/5d78dc2f-c79a-4406-ab8e-c1eaa156677c)

We seem to be able to override this by forcing all pdf links as external, which could be done in a rehype plugin, manually by overriding the anchor JSX rendering in our `Markdown` component, or by replacing all internal links with `https://klimatkollen.se/` (the deployed URL, which will get treated as external since it links to a different domain).

Of these solutions, the Markdown solution is probably preferable and if that doesn't work, we could create a minimal rehype plugin to handle special internal links that are for pdf resources.
