### ISSUE TITLE
New styling of the newsletter signup form on desktop to better highlight the signup input

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#548]
<img width="957" alt="Screenshot 2024-05-13 at 11 14 41" src="https://github.com/Klimatbyran/klimatkollen/assets/7899748/e9526620-e0b4-4130-99ec-7136625c906d">

**Comment by Greenheart** [comment]
This will be solved as part of #430 

We could add white backgrounds for the input fields, possibly with borders that are easily distinguished from the background.

Another idea: Maybe have a white background for container, since that would allow us to use black text for the main content, and gray text for the privacy policy info, while still preserving the required contrast. The current colored background doesn't allow any other text color apart from the off-white we're using.
